name: BankSystem CI Automation

on:
  push:
    branches: [ "**" ] # Kích hoạt khi push lên BẤT KỲ nhánh nào
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    # 1. Định nghĩa Matrix Strategy cho 3 hệ điều hành
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    # 2. Yêu cầu GitHub lấy hệ điều hành từ matrix để chạy
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone code từ kho lưu trữ
        uses: actions/checkout@v4

      - name: Cài đặt môi trường Java (JDK 11)
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Thực thi vòng đời Build và Test
        run: mvn -B clean package

      - name: Lưu trữ tệp .jar
        uses: actions/upload-artifact@v4
        with:
          # Gắn tên hệ điều hành vào tên file để dễ phân biệt
          name: banksystem-executable-jar-${{ matrix.os }}
          path: target/*.jar